### ISSUE TITLE
KeyError text on new document

### ISSUE THREAD

**Issue by mauritsvanrees** [kitconcept/kitconcept.voltodemo#7] opened 2019-12-05 09:22 UTC
I briefly tried the demo package yesterday and ran into an error when adding and then viewing a page in the standard Plone UI, no Volto:

```
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module zope.browserpage.simpleviewclass, line 41, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 88, in __call__
  Module z3c.pt.pagetemplate, line 173, in render
  Module chameleon.zpt.template, line 306, in render
  Module chameleon.template, line 209, in render
  Module chameleon.utils, line 75, in raise_with_traceback
  Module chameleon.template, line 187, in render
  Module 0b206ff831d6062030e8d561a0162bec, line 252, in render
  Module ffde7f6321a3c8dcfa502be6a4127128, line 684, in render_master
  Module ffde7f6321a3c8dcfa502be6a4127128, line 1240, in render_content
  Module 0b206ff831d6062030e8d561a0162bec, line 242, in __fill_content_core
  Module 0b206ff831d6062030e8d561a0162bec, line 110, in render_content_core
  Module Products.PageTemplates.expression, line 94, in __call__
  Module Products.PageTemplates.expression, line 62, in traverse
  Module OFS.Traversable, line 350, in unrestrictedTraverse
   - __traceback_info__: ([], 'text')
  Module OFS.Traversable, line 301, in unrestrictedTraverse
   - __traceback_info__: ([], 'text')
  Module plone.folder.ordered, line 241, in __getitem__
KeyError: 'text'

 - Expression: "context/text"
 - Filename:   ... egg/plone/app/contenttypes/browser/templates/document.pt
 - Location:   (line 14: col 21)
 - Source:     tal:condition="context/text"
                              ^^^^^^^^^^^^
 - Expression: "provider:plone.abovecontentbody"
 - Filename:   ... egg/Products/CMFPlone/browser/templates/main_template.pt
 - Location:   (line 94: col 70)
 - Source:     ... 
```

Recent commit 4e011e883077afd5467f7f8fa9e058c9940d9716 by @sneridagh explains why that happens: the rich text behavior was removed.

It would be fairly easy to change the document view in `plone.app.contenttypes` to use `context/text|nothing` to avoid this error.

Or maybe create a view for use in the traditional Plone UI. But that is double work.

Main question: is it the intention that this demo package is (a bit) usable in the traditional UI? Fine if the Volto blocks do not show up, but it would be nice if view and edit still work.

I realise this is just a demo package, and is there as a demo backend for the Volto UI, so feel free to say: we're not interested in supporting this in the traditional UI.

**Comment by sneridagh** [comment] 2019-12-05 10:03
@mauritsvanrees Here is the reason:
https://github.com/plone/volto/issues/1011

We run into this problem during builds (and occasionally even locally), we've been investigating, and it seems that it's because of the transform errors under some circumstances that we still have to figure it out. The builds got fixed after this change.

Since Volto is not using the Rich text fields at all, then it seemed sensible to remove it.

We have the Plone 6 kickoff sprint next week, we can try to find the best solution for that use case. I'm more +1 to the change in `plone.app.contenttypes`, easy and clean I guess. We can create a `jbot` or override the template with the package layer with the amendment, but it's more convoluted I guess.

What is your use case? Indeed this package was intended only for use in the demo, but the plans are to rename it during the sprint and use it as the Plone 6 Volto config package embryo.

**Comment by mauritsvanrees** [comment] 2019-12-05 11:36
My use case is that I wanted to check if Volto with blocks has the same error that I see in some circumstances with collective.cover tiles. It involves a rich text tile with an internal link and unicode. When using VirtualHost urls, this triggers an error in a transform.

It is interesting that you are seeing an error in a transform too in the tests. It looks different though, and I did not get any ZODB errors. Details: https://github.com/plone/Products.CMFPlone/issues/2995

**Comment by sneridagh** [comment] 2019-12-05 16:19
@mauritsvanrees maybe you are experiencing the same error that @tisto found in https://github.com/plone/volto/issues/1011? Volto does not use any of the p.tiles engine, so I don't think that your error can relate much to the Volto use case.

**Comment by sneridagh** [comment] 2023-01-09 09:07
Closing as this package is obsolete.

**Closed by sneridagh** 2023-01-09 09:07 UTC
